apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: gcr.io/gfsa-438010/nextjs-app:uat
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BASE_PATH
          value: "/uat"
      imagePullSecrets:
      - name: gcr-secret
