name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - uat
      - qa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Build Docker image for Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          docker build --no-cache -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:dev .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:dev

      - name: Build Docker image for UAT
        if: github.ref == 'refs/heads/uat'
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:uat .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:uat

      - name: Build Docker image for QA
        if: github.ref == 'refs/heads/qa'
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:qa .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:qa

      - name: Set up GKE & Install gke-gcloud-auth-plugin
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          kubectl apply -f k8/deployment.yaml
          kubectl apply -f k8/service.yaml
          kubectl apply -f k8/ingress.yaml

      - name: Deploy to UAT
        if: github.ref == 'refs/heads/uat'
        run: |
          kubectl apply -f k8/deployment.yaml
          kubectl apply -f k8/service.yaml
          kubectl apply -f k8/ingress.yaml

      - name: Deploy to QA
        if: github.ref == 'refs/heads/qa'
        run: |
          kubectl apply -f k8/deployment.yaml
          kubectl apply -f k8/service.yaml
          kubectl apply -f k8/ingress.yaml